/** Qoder CN Windows DOM, observed 2026-09-20. Profile overrides remain supported. */
export const QODER_SELECTORS = {
  input: '[contenteditable="true"][aria-label]',
  newTask: '[data-e2e="chat.new"]',
  send: 'button[data-e2e="chat.send"][data-send-button="normal"]',
  stop: 'button[data-e2e="chat.send"][data-send-button="generating"]',
  conversationWorkspace: '[data-conversation-workspace][title]',
  conversation: '[data-message-scroller-content]',
  userMessage: '[data-message-kind="user"]',
  assistantMessage: '[data-message-kind="assistant"]',
  completed: '[data-assistant-actions]',
  failed: '[data-turn-failure-card], [data-assistant-status-note="failed"]',
  interrupted: '[data-assistant-status-note="interrupted"]',
  question: '[data-pending-interaction-composer]',
  approval: '[data-pending-interaction-overlay]',
  workspace: '[data-workspace-picker-trigger]',
  workspaceSearch: 'input[aria-label="搜索工作区"]',
  workspaceItem: '[role="menuitem"][data-workspace-source="local"]',
  workspaceForm: '#workspace-editor-form',
  folderAdd: 'button[aria-describedby="workspace-folder-required"]',
  workspaceName: '#workspace-editor-form input',
  workspaceCreate: 'button[form="workspace-editor-form"][type="submit"]',
  model: 'button[aria-label^="模型:"]',
  modelMenu: '[data-chat-model-selector-menu][data-state="open"]',
  modelList: '[data-chat-model-selector-list] [role="menuitem"]',
  modelDialog: '[role="dialog"][data-state="open"]:has([role="table"][aria-label="模型参数与显示设置"])',
  levelItem: '[role="menuitemradio"]',
  permission: 'button[aria-label="访问权限"]',
  sessionLink: 'a[href^="#/chat/"]',
} as const;
export type QoderSelectorKey = keyof typeof QODER_SELECTORS;
