/**
 * 内置 agent profiles（开发计划 §7.2）。用户数据目录 agent-profiles.json 可整键覆盖。
 * 代码优先、profile 可配：真实路径属于机器/环境数据 → 默认只给结构与探测规则。
 */
import type { AgentProfile } from "../config/schema.js";

export const BUILTIN_PROFILES: Record<string, AgentProfile> = {
  codex: {
    displayName: "Codex (ChatGPT 桌面端 GUI)",
    type: "cli",
    driver: "gui",
    adapter: "codex-gui",
    // Windows 实测通过（COM 激活 + CDP）后置 ready；macOS 未验证前不启用其就绪判定。
    status: process.platform === "darwin" ? "research" : "ready",
    command: null,
    argsTemplate: [],
    promptMode: "arg",
    cwd: "task",
    env: {},
    timeoutMs: 30 * 60_000,
    killTree: "taskkill",
    authNote:
      "复用 ~/.codex 登录态（与用户手动打开的 Codex 共享；受管实例使用专属 user-data-dir）；需本机已安装 Codex 桌面端",
    executableDiscovery: {
      // MSIX(AppX) 优先查询，失败再扫盘；版本号与 WindowsApps 位置均动态获取，绝不硬编码
      dirs: [],
      fileNames: [],
      fallbackCommand: undefined,
      preferredDrives: ["C:"],
      relativePaths: [],
      appxPackageName: "OpenAI.Codex",
      installRelativeExe: ["app/ChatGPT.exe"],
      scanRoots: ["{SYSTEMDRIVE}/Program Files/WindowsApps"],
      scanPattern: "OpenAI.Codex_*_x64__*/app/ChatGPT.exe",
    },
    gui: {
      cdpPort: 9333,
      cdpPortAuto: true,
      cdpPortRange: 30,
      exeArgs: [],
      windowMode: "reuse",
      // Codex 冷启动（MSIX 首帧 + 渲染）可能超过 60s；实测约 60-90s，放宽到 150s
      launchTimeoutMs: 150_000,
      pollIntervalMs: 3_000,
      stableRounds: 4,
      idleTimeoutMs: 10 * 60_000,
      cdpSendTimeoutMs: 15_000,
      progressIntervalMs: 30_000,
      modelSwitch: true,
      modeSwitch: false,
      freshSession: true,
      selectors: {},
      modelRequired: true,
      activation: "msix-com",
      userDataDir: "{LOCALAPPDATA}/tianshu-mcp/codex-gui/profile",
      appxPackageName: "OpenAI.Codex",
      permissionMode: "完全访问",
      defaultPermissionMode: "完全访问",
      fixPlanDir: ".zcode/plans",
      defaultAutoFixRounds: 5,
    },
    note: "Codex 桌面端为 MSIX 商店包：GUI 宿主 ChatGPT.exe 无法 CreateProcess 直启（策略拒绝），须经 IApplicationActivationManager COM 激活并注入专属 user-data-dir + --remote-debugging-port；详见 docs/codex-gui-cdp.md",
  },
  zcode: {
    displayName: "Zcode (ZCode 桌面)",
    type: "cli",
    driver: "gui",
    adapter: "zcode-gui",
    // macOS 真机证据完成前必须保持非 ready；research 仍允许已安装机器执行诊断/任务。
    status: "research",
    command: null,
    argsTemplate: [],
    promptMode: "arg",
    cwd: "task",
    env: {},
    timeoutMs: 30 * 60_000,
    killTree: "taskkill",
    authNote: "复用本机 ZCode 登录态",
    executableDiscovery: {
      dirs: [
        "{ProgramFiles}/ZCode",
        "{ProgramFiles(x86)}/ZCode",
        "{LOCALAPPDATA}/Programs/ZCode",
        "{LOCALAPPDATA}/ZCode",
        "/Applications/ZCode.app/Contents/MacOS",
        "{HOME}/Applications/ZCode.app/Contents/MacOS",
      ],
      fileNames: ["ZCode.exe", "ZCode"],
      preferredDrives: ["D:"],
      relativePaths: ["Z-Code/ZCode/ZCode.exe", "ZCode/ZCode.exe"],
      installRelativeExe: [],
      scanRoots: [],
    },
    gui: {
      cdpPort: 9333,
      cdpPortAuto: true,
      cdpPortRange: 30,
      exeArgs: ["--remote-debugging-port=<port>"],
      windowMode: "reuse",
      launchTimeoutMs: 60_000,
      pollIntervalMs: 3_000,
      stableRounds: 4,
      idleTimeoutMs: 10 * 60_000,
      cdpSendTimeoutMs: 15_000,
      progressIntervalMs: 30_000,
      modelSwitch: true,
      modeSwitch: false,
      freshSession: true,
      selectors: {},
      modelRequired: true,
      activation: "spawn",
      permissionMode: "完全访问",
      defaultPermissionMode: "完全访问",
      defaultAutoFixRounds: 2,
    },
    note: "ZCode Electron CDP GUI adapter。macOS 真机闭环证据完成前保持 research；已安装环境可探测和执行。",
  },
  traework: {
    displayName: "TraeWork (TRAE SOLO CN)",
    type: "cli",
    driver: "gui",
    adapter: "traework-gui",
    status: "ready",
    command: null,
    argsTemplate: [],
    promptMode: "arg",
    cwd: "task",
    env: {},
    timeoutMs: 30 * 60_000,
    killTree: "taskkill",
    authNote: "复用 TraeWork 桌面端登录态；窗口需保持可见（发送依赖模拟输入）",
    executableDiscovery: {
      dirs: [
        "D:/TRAE Work CN",
        "{ProgramFiles}/TRAE WORK CN",
        "{ProgramFiles(x86)}/TRAE WORK CN",
        "{LOCALAPPDATA}/Programs/TRAE WORK CN",
        "{LOCALAPPDATA}/TRAE WORK CN",
        "{APPDATA}/TRAE SOLO CN",
        "/Applications/TraeWork.app/Contents/MacOS",
        "/Applications/Trae CN.app/Contents/MacOS",
      ],
      fileNames: ["TRAE SOLO CN.exe", "TraeWork", "TraeWork CN", "Trae CN"],
      fallbackCommand: undefined,
      preferredDrives: [],
      relativePaths: [],
      installRelativeExe: [],
      scanRoots: [],
    },
    gui: {
      cdpPort: 9222,
      cdpPortAuto: true,
      cdpPortRange: 20,
      exeArgs: ["--remote-debugging-port=<port>"],
      windowMode: "reuse",
      launchTimeoutMs: 60_000,
      pollIntervalMs: 3_000,
      stableRounds: 12,
      idleTimeoutMs: 10 * 60_000,
      cdpSendTimeoutMs: 15_000,
      progressIntervalMs: 30_000,
      modelSwitch: true,
      modeSwitch: true,
      freshSession: true,
      selectors: {},
      modelRequired: false,
      activation: "spawn",
    },
    note: "GUI 驱动（CDP）：T1 旧结论（无头 CLI 不存在）成立，但实测 --remote-debugging-port 可驱动聊天 UI（v1.107.1 已验证连接与关键选择器）。详见 docs/traework-cdp.md",
  },
};

export const BUILTIN_PROFILE_IDS = Object.keys(BUILTIN_PROFILES);
