/**
 * 内置 agent profiles（开发计划 §7.2）。用户数据目录 agent-profiles.json 可整键覆盖。
 * 代码优先、profile 可配：真实路径属于机器/环境数据 → 默认只给结构与探测规则。
 */
import type { AgentProfile } from "../config/schema.js";

export const BUILTIN_PROFILES: Record<string, AgentProfile> = {
  codex: {
    displayName: "Codex (OpenAI 桌面端 CLI)",
    type: "cli",
    driver: "spawn",
    status: "ready",
    command: null,
    argsTemplate: ["exec", "<prompt:arg>", "--skip-git-repo-check", "--sandbox", "workspace-write"],
    promptMode: "arg",
    cwd: "task",
    env: {},
    timeoutMs: 30 * 60_000,
    killTree: "taskkill",
    authNote:
      "复用 ~/.codex 登录态（与桌面端同账号）；需本机已装 Codex 桌面端；勿与 --approve-for-me 同用（实测互斥）",
    executableDiscovery: {
      dirs: [
        "{LOCALAPPDATA}/OpenAI/Codex/bin",
        "{USERPROFILE}/AppData/Local/OpenAI/Codex/bin",
        "/Applications/Codex.app/Contents/Resources/app/bin",
      ],
      fileNames: ["codex.exe", "codex"],
      fallbackCommand: "codex",
      preferredDrives: [],
      relativePaths: [],
    },
    note: "M2 真实冒烟已定稿（见 docs/m2-smoke-record.md）：--sandbox workspace-write 非交互通过",
  },
  zcode: {
    displayName: "Zcode (ZCode 桌面)",
    type: "cli",
    driver: "gui",
    adapter: "zcode-gui",
    // macOS 真机证据完成前必须保持非 ready；research 仍允许已安装机器执行诊断/任务。
    status: "research",
    command: null,
    argsTemplate: [],
    promptMode: "arg",
    cwd: "task",
    env: {},
    timeoutMs: 30 * 60_000,
    killTree: "taskkill",
    authNote: "复用本机 ZCode 登录态",
    executableDiscovery: {
      dirs: [
        "{ProgramFiles}/ZCode",
        "{ProgramFiles(x86)}/ZCode",
        "{LOCALAPPDATA}/Programs/ZCode",
        "{LOCALAPPDATA}/ZCode",
        "/Applications/ZCode.app/Contents/MacOS",
        "{HOME}/Applications/ZCode.app/Contents/MacOS",
      ],
      fileNames: ["ZCode.exe", "ZCode"],
      preferredDrives: ["D:"],
      relativePaths: ["Z-Code/ZCode/ZCode.exe", "ZCode/ZCode.exe"],
    },
    gui: {
      cdpPort: 9333,
      cdpPortAuto: true,
      cdpPortRange: 30,
      exeArgs: ["--remote-debugging-port=<port>"],
      windowMode: "reuse",
      launchTimeoutMs: 60_000,
      pollIntervalMs: 3_000,
      stableRounds: 4,
      idleTimeoutMs: 10 * 60_000,
      cdpSendTimeoutMs: 15_000,
      progressIntervalMs: 30_000,
      modelSwitch: true,
      modeSwitch: false,
      freshSession: true,
      selectors: {},
      modelRequired: true,
      defaultPermissionMode: "完全访问",
      defaultAutoFixRounds: 2,
    },
    note: "ZCode Electron CDP GUI adapter。macOS 真机闭环证据完成前保持 research；已安装环境可探测和执行。",
  },
  traework: {
    displayName: "TraeWork (TRAE SOLO CN)",
    type: "cli",
    driver: "gui",
    adapter: "traework-gui",
    status: "ready",
    command: null,
    argsTemplate: [],
    promptMode: "arg",
    cwd: "task",
    env: {},
    timeoutMs: 30 * 60_000,
    killTree: "taskkill",
    authNote: "复用 TraeWork 桌面端登录态；窗口需保持可见（发送依赖模拟输入）",
    executableDiscovery: {
      dirs: [
        "D:/TRAE Work CN",
        "{ProgramFiles}/TRAE WORK CN",
        "{ProgramFiles(x86)}/TRAE WORK CN",
        "{LOCALAPPDATA}/Programs/TRAE WORK CN",
        "{LOCALAPPDATA}/TRAE WORK CN",
        "{APPDATA}/TRAE SOLO CN",
        "/Applications/TraeWork.app/Contents/MacOS",
        "/Applications/Trae CN.app/Contents/MacOS",
      ],
      fileNames: ["TRAE SOLO CN.exe", "TraeWork", "TraeWork CN", "Trae CN"],
      fallbackCommand: undefined,
      preferredDrives: [],
      relativePaths: [],
    },
    gui: {
      cdpPort: 9222,
      cdpPortAuto: true,
      cdpPortRange: 20,
      exeArgs: ["--remote-debugging-port=<port>"],
      windowMode: "reuse",
      launchTimeoutMs: 60_000,
      pollIntervalMs: 3_000,
      stableRounds: 12,
      idleTimeoutMs: 10 * 60_000,
      cdpSendTimeoutMs: 15_000,
      progressIntervalMs: 30_000,
      modelSwitch: true,
      modeSwitch: true,
      freshSession: true,
      selectors: {},
      modelRequired: false,
    },
    note: "GUI 驱动（CDP）：T1 旧结论（无头 CLI 不存在）成立，但实测 --remote-debugging-port 可驱动聊天 UI（v1.107.1 已验证连接与关键选择器）。详见 docs/traework-cdp.md",
  },
};

export const BUILTIN_PROFILE_IDS = Object.keys(BUILTIN_PROFILES);
